sudo: required

language: node_js

node_js:
  - node
  - "8"

services:
  - docker

cache:
  directories:
    - "node_modules"

script: # the build step
  - npm run tsc
  - docker build -t markieo/slack-clone-api .
