sudo: required

language: node_js

node_js:
  - node

services:
  - docker

cache:
  directories:
    - "node_modules"

script: # the build step
  - npm run tsc
  - docker build -t markieo/slack-clone-api:latest .
  - docker push markieo/slack-clone-api 
